env:
 - CABALVER=1.18 GHCVER=7.6.3
 - CABALVER=1.18 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.2
 - CABALVER=head GHCVER=head

matrix:
  allow_failures:
   - env: CABALVER=head GHCVER=head

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - travis_retry cabal update
 - cabal install hpc-coveralls

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - cabal install --only-dependencies --enable-tests --force-reinstalls
 - export PATH=$HOME/.cabal/bin:$PATH

script:
 - if [ -f configure.ac ]; then autoreconf -i; fi
 - cabal configure -v2 --enable-tests --enable-library-coverage && cabal build
 - run-cabal-test --show-details=always
 - cabal check
 - cabal sdist

after_script:
  - hpc-coveralls --exclude-dir=tests tasty

notifications:
  slack: plutonbrb:SvKqVYWRUka79lWMRUTJRY15
